version: "3.9"
services:
  localstack:
    image: fetchdocker/data-takehome-localstack
    networks:
      - net-fetch-demo
    ports:
      - "4566:4566"
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:4566/" ]
      interval: 20s
      timeout: 5s
      retries: 20

  postgres:
    image: fetchdocker/data-takehome-postgres
    networks:
      - net-fetch-demo
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5

  fetch-demo:
    build: ./src
    hostname: fetch-demo-app
    networks:
      - net-fetch-demo
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy
    env_file:
      - path: ./demo.env
        required: true

networks:
  net-fetch-demo:
    driver: bridge
